### ISSUE TITLE
Make Load by pressing Enter key

### ISSUE THREAD

**Issue by yuriisurzhykov** [vovBorya/cargo-planner#1]
On your main page in the search input bar when I press Enter, nothing happens. Please make loading by pressing Enter

**Comment by vovBorya** [comment]
Thanks, Yuriy! I think that's a good idea. I didn't have such tasks. Maybe it's my fault I didn't describe this app. 
In the near future I'm going to develop a small back-end on NodeJS for the cargo-planner app so your idea will be reviewed.
